// Redux 年代的 Action Types 定義
export const CHAT_ACTION_TYPES = {
  // 房間統計
  FETCH_ROOM_STATS_REQUEST: 'FETCH_ROOM_STATS_REQUEST',
  FETCH_ROOM_STATS_SUCCESS: 'FETCH_ROOM_STATS_SUCCESS',
  FETCH_ROOM_STATS_FAILURE: 'FETCH_ROOM_STATS_FAILURE',

  // 使用者暱稱
  UPDATE_NICKNAME_REQUEST: 'UPDATE_NICKNAME_REQUEST',
  UPDATE_NICKNAME_SUCCESS: 'UPDATE_NICKNAME_SUCCESS',
  UPDATE_NICKNAME_FAILURE: 'UPDATE_NICKNAME_FAILURE',

  // 購買點數
  PURCHASE_POINTS_REQUEST: 'PURCHASE_POINTS_REQUEST',
  PURCHASE_POINTS_SUCCESS: 'PURCHASE_POINTS_SUCCESS',
  PURCHASE_POINTS_FAILURE: 'PURCHASE_POINTS_FAILURE',

  // 使用點數
  USE_POINTS_REQUEST: 'USE_POINTS_REQUEST',
  USE_POINTS_SUCCESS: 'USE_POINTS_SUCCESS',
  USE_POINTS_FAILURE: 'USE_POINTS_FAILURE',

  // 聊天點數餘額
  FETCH_POINTS_BALANCE_REQUEST: 'FETCH_POINTS_BALANCE_REQUEST',
  FETCH_POINTS_BALANCE_SUCCESS: 'FETCH_POINTS_BALANCE_SUCCESS',
  FETCH_POINTS_BALANCE_FAILURE: 'FETCH_POINTS_BALANCE_FAILURE',

  // SignalR 連線
  SIGNALR_CONNECT_REQUEST: 'SIGNALR_CONNECT_REQUEST',
  SIGNALR_CONNECT_SUCCESS: 'SIGNALR_CONNECT_SUCCESS',
  SIGNALR_CONNECT_FAILURE: 'SIGNALR_CONNECT_FAILURE',
  SIGNALR_DISCONNECT: 'SIGNALR_DISCONNECT',

  // 訊息
  SEND_MESSAGE_REQUEST: 'SEND_MESSAGE_REQUEST',
  SEND_MESSAGE_SUCCESS: 'SEND_MESSAGE_SUCCESS',
  SEND_MESSAGE_FAILURE: 'SEND_MESSAGE_FAILURE',
  RECEIVE_MESSAGE: 'RECEIVE_MESSAGE',

  // UI 狀態
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SET_CONNECTION_STATUS: 'SET_CONNECTION_STATUS',
  SHOW_TOAST: 'SHOW_TOAST',
  HIDE_TOAST: 'HIDE_TOAST',
} as const
